### PR TITLE
added german translation (Du)

### PR DESCRIPTION
**Pull request by RobertHeim**

### CODE REVIEW

**Comment by rfdy** [comment]
Thank you! merged.

**Comment by rfdy** [comment]
Sorry about the last comment, was meant for another pull request.

Thank you for providing the translation! We have however now a lot more strings in the language file, would it be possible to translate these as well?

**Comment by RobertHeim** [comment]
Hi, yes I can translate them. I wait for the extension to become RC so I do not need to translate them multiple times in case you change things until RC. Let me know when the ext hits RC, then I can do it.

**Comment by Galixte** [comment]
close it, will be insert in a new PR.

**Comment by Galixte** [comment]
included and udpdated here: https://github.com/rfdy/trader/pull/30

**Pull request closed without merging**
