### PR TITLE
Create common.php

### PR DESCRIPTION
**Pull request by Maskinisten**
Swedish translation

### CODE REVIEW

**Comment by rfdy** [comment]
Thank you for providing the translation! We have however now a lot more strings in the language file, would it be possible to translate these as well?

**Comment by Maskinisten** [comment]
Sure! How do I do that the easiest way? (New to GitHub)

**Comment by rfdy** [comment]
Thanks! The easiest would be to merge all the changes from my branch into yours, that will bring in the new strings but keep in your branch the changes that you already made. Then after you commit the translations update the pull request with your second commit.

**Comment by Maskinisten** [comment]
Thank you! But I dont find any way to merge ... is it a "re-fork"?

**Comment by rfdy** [comment]
I believe all that you need to do is a pull with remote set to rfdy (mine) rather than your repo. This would bring in all the recent changes. Then you can commit back to your repo.

A somewhat less pretty alternative is to create another fork, then copy the one added file, adjust it and commit that back to the new fork.

Thanks!

**Comment by Maskinisten** [comment]
Ah, I have to say that I am not using the Windows application, I try to work online. The port is blocked here at work.

**Comment by Maskinisten** [comment]
I have updated the missing textstrings "manually". Do you receive them?

**Comment by rfdy** [comment]
yes, and merged it in, thank you!

**Pull request merged**
