### PR TITLE
Update for ENGLISH/NL/SV translations for Trader ext + Add missing language keys

### PR DESCRIPTION
**Pull request by Galixte**
- Update for ENGLISH/NL/SV translations for common.php file: Add missing language key present in the core files

### CODE REVIEW

**Comment by Galixte** [comment]
Related PR: https://github.com/rfdy/trader/pull/11

**Comment by mhakfoort** [comment]
REQUIERED should be REQUIRED and MEMBRES should be MEMBERS in the language keys. Good work on all these though :)

**Comment by Galixte** [comment]
Thanks it's fixed ;)

**Comment by Galixte** [comment]
Hi @rfdy,

it's OK for me, could you take a look ?

**Comment by Galixte** [comment]
Done, see that: https://github.com/rfdy/trader/commit/5d338160138782ab877efe2cca75e9199410dc80

**Pull request closed without merging**
